### PR TITLE
Global scope support (fixed #65 #64)

### LINKED ISSUE #65: ThrowsScope: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given
```
/app $ phpstan analyse --debug
Note: Using configuration file /app/phpstan.neon.
/app/.../Resources/config/form.php

Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in src/Rules/ThrowsScope.php:96
Stack trace:
#0 src/Rules/ThrowsScope.php(96): array_keys(NULL)
#1 src/Rules/ThrowsScope.php(82): Pepakriz\PHPStanExceptionRules\Rules\ThrowsScope->isExceptionCaught('Symfony\\Compone...')
#2 [internal function]: Pepakriz\PHPStanExceptionRules\Rules\ThrowsScope->Pepakriz\PHPStanExceptionRules\Rules\{closure}('Symfony\\Compone...')
#3 src/Rules/ThrowsScope.php(83): array_filter(Array, Object(Closure))
#4 src/Rules/ThrowsPhpDocRule.php(639): Pepakriz\PHPStanExceptionRules\Rules\ThrowsScope->filterExceptionsByUncaught(Array)
#5 ... in src/Rules/ThrowsScope.php on line 96
```

### PR DESCRIPTION
**Pull request by pepakriz**

### CODE REVIEW

File: tests/src/Rules/ThrowsPhpDocRuleTest.php [hunk 1]
```diff
@@ -69,6 +69,7 @@ protected function getRule(): Rule
 			$this->createThrowsAnnotationReader(),
 			$this->createBroker(),
 			$this->reportUnusedCatchesOfUncheckedExceptions,
+			true,
```
Comment (marcospassos) [inline tests/src/Rules/ThrowsPhpDocRuleTest.php]: This configuration is test-specific, should we use a flag property here?

**Review by marcospassos — CHANGES_REQUESTED** [review]

**Review by marcospassos — APPROVED** [review]

**Comment by marcospassos** [comment]
Nice feature. I think it deserves a note in the readme file.

File: tests/src/Rules/ThrowsPhpDocRuleTest.php (hunk 1 above)
Comment (pepakriz) [reply tests/src/Rules/ThrowsPhpDocRuleTest.php]: You're right. I've changed it
